- README.md
README has been updated to fix grammatical errors.
> Revise README grammer

- Makefile
This seems like the expected behavior.
cc: @shepting
> Update Makefile to clean Buck when `clean` is run

- .buckconfig
Makes testing unit tests in Xcode a bit easier.
> Generate all targets

- .buckconfig
> Make 'buck project' ignore tools directory

- README.md
> Correct instructions for installing buck

- Config/buck_rule_macros.bzl
> additional_external_linker_flags -> additional_exported_linker_flags

- Config/buck_rule_macros.bzl
Default parameters are fine. But let's not hardcode visibility anywhere.
> Do not override visibility

- Libraries/SwiftAndObjc/Sources/MyBridgedSwiftClassInMixedModule.swift
- Libraries/SwiftAndObjc/Sources/MyObjcClassInMixedModule.m
Proving this is possible in a library.
> Import Swift from Objective-C

- Config/buck_rule_macros.bzl
Don't repeat yourself
cc @shepting
> Check warnings flags once, not twice

- App/BUCK
- App/ViewController.swift
- Libraries/ObjcAndSwift/BUCK
- Libraries/ObjcAndSwift/Sources/MyBridgedObjcClassInMixedModule.h
- Libraries/ObjcAndSwift/Sources/MyBridgedObjcClassInMixedModule.m
- Libraries/ObjcAndSwift/Sources/MyBridgedSwiftClassInMixedModule.swift
- Libraries/ObjcAndSwift/Sources/MySwiftClassInMixedModule.swift
- Libraries/ObjcAndSwift/Tests/Info.plist
- Libraries/ObjcAndSwift/Tests/Tests.swift
> Create a module where Swift can see Objective C without a bridging header

- App/BUCK
- App/BuckSupportFiles/Dummy.swift
- App/Tests/BUCK
- App/Tests/BuckSampleTests.swift
- Libraries/Swift2/Tests/SomeSwift2Tests.swift
>  Make application tests @testable import ExampleApp

- App/BUCK
- scripts/sample.sh
This PR demonstrates how to add a Build Phase Script to our sample project both as pre-build and post-build.
This is how it looks in the generated project:
cc @shepting @dfed @bachand @qyang-nj
> Add Build Phase Scripts

- README.md
Helps resolve https://github.com/airbnb/BuckSample/issues/60 for everyone
> Add note to Install step re installing Java 8

- App/BUCK
- Config/buck_rule_macros.bzl
- Makefile
That was surprisingly easy. Thank you @thedavidharris for the idea!
This PR resolves #18.
> Get UITests working with Buck

- Libraries/Objc1/BUCK
- Libraries/Objc1/Objc1-umbrella.h
- Libraries/Objc1/Objc1.modulemap
- Libraries/ObjcAndSwift/Sources/MyBridgedSwiftClassInMixedModule.swift
Following up on https://github.com/airbnb/BuckSample/pull/73#discussion_r272808531 and https://github.com/airbnb/BuckSample/pull/73#discussion_r272808736
cc @gsabran
> Remove unnecessary files and add better comments

- App/BUCK
Documenting what we've learned from https://github.com/airbnb/BuckSample/pull/70#issuecomment-481022463
cc @gsabran @bogo
> Add comment to XCUITests target

- App/BUCK
- App/WatchApplication/Info.plist
- App/WatchExtension/Info.plist
If the bundle_identifier function is modified, it won't match what's in the Info.plist
> Use bundle identifier function

- App/ViewController.swift
- Libraries/Cpp1/Sources/CppClass1.h
- Libraries/Cpp1/Sources/CppClass1.mm
- Libraries/Cpp1/Tests/Tests.swift
Rename add functions for better use in Swift
> Add unit tests for Cpp1 library

- .buckconfig
- App/ViewController.swift
- BuildConfigurations/Release.buckconfig
- Config/configs.bzl
- Makefile
Hey there, I used this sample to add Buck to a very big project and it was very helpful -- thanks for that!
I bumped into more than a few things that aren't covered here, so I thought I could contribute them back to the sample. In this case, I added support for a release build configuration that changes the optimization setting in the CLI and Xcode. I'm not sure how you guys deal with this in Airbnb, so let me know if I'm too far off!
> Add Release build configuration

- README.md
I think this makes the project more accessible.
cc: @qyang-nj @dfed @shepting
> Add some helpful commands to README

- .circleci/config.yml
> [Xcode] Update Xcode version

- BuckLocal/remap_debug_source_path.sh
- BuckLocal/ruby_scripts/project_generator.rb
- Makefile
> Fix BuckLocal compilation on Xcode 12 and Big Sur

- .gitignore
- App/BUCK
- BuckLocal/ruby_scripts/project_generator.rb
- Config/buck_local.bzl
**Step 1: `make buck_local_project`**
**Step 2: `Cmd + U` to build and run XCUITest for the Example App**
**Step 3:** Wait and see the UI test results.
@qyang-nj @shepting
> Get XCUITest working in BuckLocal Xcode project
